### ISSUE TITLE
Which Java Web Framework ?

### ISSUE THREAD

**Issue by MorrisLaw** [MorrisLaw/house-market-values#5]
Hilario, Margarito. There are tons of frameworks out there for creating Java web applications.

https://zeroturnaround.com/rebellabs/java-web-frameworks-index-by-rebellabs/

Review this and put on here which you want to use.

**Comment by MorrisLaw** [comment]
Assigning you hilario, I'll assign Margarito as well once he accepts.

**Comment by hilarior12** [comment]
Spring MVC sounds like the way to go. 
Spring boot is also consistently growing.

**Comment by MorrisLaw** [comment]
https://stackoverflow.com/a/32923000

Based on his answer, "Spring MVC is a framework to be used in web applications and Spring boot is a Spring based production-ready project initializer." Let's go with Spring boot because it contains Spring MVC. Good call. We'll use this.
